#!/usr/bin/env node
/**
 * @fileoverview Code generator for analytics events
 * Reads events.yml and generates TypeScript and Rust type definitions
 * 
 * Deterministic constraints:
 * - Keys sorted alphabetically
 * - No timestamps or absolute paths in output
 * - @generated header added
 * - Only processes active events (deprecated events ignored)
 */

import fs from 'fs';
import path from 'path';
import yaml from 'yaml';

// Paths (relative to repo root)
const REPO_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../../..');
const EVENTS_YML = path.join(REPO_ROOT, 'apps/desktop/analytics/events.yml');
const TS_OUTPUT = path.join(REPO_ROOT, 'apps/desktop/client/src/lib/analytics-events.gen.ts');
const RUST_OUTPUT = path.join(REPO_ROOT, 'apps/desktop/client/src-tauri/src/analytics_events_gen.rs');

const TS_HEADER = `/**
 * @generated
 * This file is auto-generated by codegen.mjs from events.yml
 * DO NOT EDIT MANUALLY
 */

`;

const RUST_HEADER = `// @generated
// This file is auto-generated by codegen.mjs from events.yml
// DO NOT EDIT MANUALLY

`;

/**
 * Load and validate events.yml
 */
function loadEvents() {
  if (!fs.existsSync(EVENTS_YML)) {
    throw new Error(`events.yml not found at ${EVENTS_YML}`);
  }

  const content = fs.readFileSync(EVENTS_YML, 'utf-8');
  const data = yaml.parse(content);

  // Validate schema version
  if (!data.schema_version) {
    throw new Error('events.yml missing schema_version');
  }

  if (data.schema_version !== '1.0') {
    throw new Error(`Unsupported schema_version: ${data.schema_version}`);
  }

  // Validate posthog config
  if (!data.posthog?.project_id) {
    throw new Error('events.yml missing posthog.project_id');
  }

  // Extract active events only
  const activeEvents = {};
  for (const [name, event] of Object.entries(data.events || {})) {
    if (event.status === 'active') {
      activeEvents[name] = event;
    }
  }

  return {
    schemaVersion: data.schema_version,
    posthog: data.posthog,
    events: activeEvents,
  };
}

/**
 * Map YAML type to TypeScript type
 */
function yamlTypeToTs(yamlType) {
  const typeMap = {
    'string': 'string',
    'number': 'number',
    'boolean': 'boolean',
    'object': 'Record<string, unknown>',
    'array': 'unknown[]',
  };
  return typeMap[yamlType] || 'unknown';
}

/**
 * Map YAML type to Rust type
 */
function yamlTypeToRust(yamlType) {
  const typeMap = {
    'string': 'String',
    'number': 'f64',
    'boolean': 'bool',
    'object': 'serde_json::Value',
    'array': 'Vec<serde_json::Value>',
  };
  return typeMap[yamlType] || 'serde_json::Value';
}

/**
 * Generate TypeScript types
 */
function generateTypeScript(events) {
  let output = TS_HEADER;

  // Generate AppEventMap
  output += `export interface AppEventMap {\n`;
  
  const sortedEvents = Object.keys(events).sort();
  
  for (const eventName of sortedEvents) {
    const event = events[eventName];
    const props = event.props || {};
    
    // Build props interface
    const propEntries = Object.entries(props)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([propName, propType]) => `    ${propName}: ${yamlTypeToTs(propType)};`)
      .join('\n');
    
    output += `  ${eventName}: {\n`;
    if (propEntries) {
      output += propEntries + '\n';
    }
    output += `  };\n`;
  }
  
  output += `}\n\n`;

  // Generate trackTypedEvent helper
  output += `/**
 * Type-safe event tracking helper
 * @param event - Event name (must be a key of AppEventMap)
 * @param props - Event properties (must match the event's type)
 */
export function trackTypedEvent<K extends keyof AppEventMap>(
  event: K,
  props: AppEventMap[K]
): void {
  // Implementation will be provided by analytics.ts
  // This is just the type signature
  console.log('trackTypedEvent:', event, props);
}
`;

  return output;
}

/**
 * Generate Rust types
 */
function generateRust(events) {
  let output = RUST_HEADER;
  
  output += `//! Auto-generated analytics event types
//! DO NOT EDIT MANUALLY

use serde::{Serialize, Deserialize};

/// Analytics event names
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Event {
`;

  const sortedEvents = Object.keys(events).sort();
  
  for (const eventName of sortedEvents) {
    // Convert snake_case to PascalCase for Rust enum variant
    const pascalName = eventName
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    
    output += `    ${pascalName},\n`;
  }
  
  output += `}\n\n`;

  // Generate props structs
  for (const eventName of sortedEvents) {
    const event = events[eventName];
    const props = event.props || {};
    
    if (Object.keys(props).length === 0) {
      continue;
    }

    const pascalName = eventName
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');

    output += `/// Properties for ${eventName} event\n`;
    output += `#[derive(Debug, Clone, Serialize, Deserialize)]\n`;
    output += `pub struct ${pascalName}Props {\n`;
    
    const sortedProps = Object.entries(props).sort(([a], [b]) => a.localeCompare(b));
    for (const [propName, propType] of sortedProps) {
      const rustType = yamlTypeToRust(propType);
      // Convert snake_case to snake_case (Rust field naming)
      output += `    pub ${propName}: ${rustType},\n`;
    }
    
    output += `}\n\n`;
  }

  // Generate Event impl with event_name method
  output += `impl Event {
    /// Get the snake_case event name string
    pub fn as_str(&self) -> &'static str {
        match self {
`;

  for (const eventName of sortedEvents) {
    const pascalName = eventName
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    
    output += `            Event::${pascalName} => "${eventName}",\n`;
  }

  output += `        }
    }
}

impl std::fmt::Display for Event {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
`;

  return output;
}

/**
 * Main entry point
 */
function main() {
  console.log('Loading events.yml...');
  const { events, schemaVersion, posthog } = loadEvents();
  
  console.log(`Found ${Object.keys(events).length} active events (schema v${schemaVersion})`);
  console.log(`PostHog project: ${posthog.project_id}`);

  // Generate TypeScript
  console.log('Generating TypeScript types...');
  const tsOutput = generateTypeScript(events);
  fs.writeFileSync(TS_OUTPUT, tsOutput, 'utf-8');
  console.log(`✓ ${TS_OUTPUT}`);

  // Generate Rust
  console.log('Generating Rust types...');
  const rustOutput = generateRust(events);
  fs.writeFileSync(RUST_OUTPUT, rustOutput, 'utf-8');
  console.log(`✓ ${RUST_OUTPUT}`);

  console.log('\nCode generation complete!');
}

// Run
try {
  main();
} catch (err) {
  console.error('Code generation failed:', err.message);
  process.exit(1);
}
