/**
 * @generated
 * This file is auto-generated by codegen.mjs from events.yml
 * DO NOT EDIT MANUALLY
 */

export interface AppEventMap {
  app_update_check: {
    source: string;
  };
  app_update_checked: {
    result: string;
    source: string;
  };
  app_update_failed: {
    detail: string;
    source: string;
    stage: string;
  };
  app_update_installed: {
    source: string;
    to: string;
  };
  diag_identity_failed: {
    reason: string;
  };
  diag_ipc_timeout: {
    command: string;
    error_code: string;
    timeout_ms: number;
  };
  diag_logs_open_failed: {
    error: string;
    stage: string;
  };
  diag_native_main_unresponsive: {
    error_code: string;
  };
  diag_rust_panic: {
    backtrace: string;
    error_code: string;
    message: string;
  };
  diag_state_load_failed: {
    reason: string;
  };
  diag_task_spawn_failed: {
    error: string;
    task: string;
  };
  diag_webview_recovered: {
    error_code: string;
    freeze_duration_ms: number;
  };
  diag_webview_unresponsive: {
    error_code: string;
    missed_js_beats: number;
    threshold_s: number;
  };
  js_error: {
    message: string;
  };
  js_heartbeat: {
    seq: number;
    uptime_sec: number;
  };
  js_launch: {
  };
  js_unhandled_rejection: {
    reason: string;
  };
  logs_open: {
  };
  panel_close: {
    panel_id: string;
    via: string;
  };
  panel_open: {
    panel_id: string;
    via: string;
  };
  rust_exit: {
    pending_flushed: boolean;
    prev_session_id: string;
    reason: string;
    uptime_s: number;
    via: string;
  };
  rust_heartbeat: {
    seq: number;
  };
  rust_launch: {
    version: string;
  };
  state_load: {
    duration_ms: number;
    tasks: number;
  };
  state_sync: {
    mock: boolean;
    tasks: number;
  };
  task_run: {
    task: string;
  };
}

/**
 * Type-safe event tracking helper
 * @param event - Event name (must be a key of AppEventMap)
 * @param props - Event properties (must match the event's type)
 */
export function trackTypedEvent<K extends keyof AppEventMap>(
  event: K,
  props: AppEventMap[K]
): void {
  // Implementation will be provided by analytics.ts
  // This is just the type signature
  console.log('trackTypedEvent:', event, props);
}
