// @generated
// This file is auto-generated by codegen.mjs from events.yml
// DO NOT EDIT MANUALLY

//! Auto-generated analytics event types
//! DO NOT EDIT MANUALLY

use serde::{Serialize, Deserialize};

/// Analytics event names
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Event {
    AppUpdateCheck,
    AppUpdateChecked,
    AppUpdateFailed,
    AppUpdateInstalled,
    DiagIdentityFailed,
    DiagIpcTimeout,
    DiagLogsOpenFailed,
    DiagNativeMainUnresponsive,
    DiagRustPanic,
    DiagStateLoadFailed,
    DiagTaskSpawnFailed,
    DiagWebviewRecovered,
    DiagWebviewUnresponsive,
    JsError,
    JsHeartbeat,
    JsLaunch,
    JsUnhandledRejection,
    LogsOpen,
    PanelClose,
    PanelOpen,
    RustExit,
    RustHeartbeat,
    RustLaunch,
    StateLoad,
    StateSync,
    TaskRun,
}

/// Properties for app_update_check event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppUpdateCheckProps {
    pub source: String,
}

/// Properties for app_update_checked event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppUpdateCheckedProps {
    pub result: String,
    pub source: String,
}

/// Properties for app_update_failed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppUpdateFailedProps {
    pub detail: String,
    pub source: String,
    pub stage: String,
}

/// Properties for app_update_installed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppUpdateInstalledProps {
    pub source: String,
    pub to: String,
}

/// Properties for diag_identity_failed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagIdentityFailedProps {
    pub reason: String,
}

/// Properties for diag_ipc_timeout event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagIpcTimeoutProps {
    pub command: String,
    pub error_code: String,
    pub timeout_ms: f64,
}

/// Properties for diag_logs_open_failed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagLogsOpenFailedProps {
    pub error: String,
    pub stage: String,
}

/// Properties for diag_native_main_unresponsive event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagNativeMainUnresponsiveProps {
    pub error_code: String,
    pub stalled_ms: f64,
}

/// Properties for diag_rust_panic event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagRustPanicProps {
    pub backtrace: String,
    pub error_code: String,
    pub message: String,
}

/// Properties for diag_state_load_failed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagStateLoadFailedProps {
    pub reason: String,
}

/// Properties for diag_task_spawn_failed event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagTaskSpawnFailedProps {
    pub error: String,
    pub task: String,
}

/// Properties for diag_webview_recovered event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagWebviewRecoveredProps {
    pub error_code: String,
    pub freeze_duration_ms: f64,
}

/// Properties for diag_webview_unresponsive event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagWebviewUnresponsiveProps {
    pub error_code: String,
    pub missed_js_beats: f64,
    pub threshold_s: f64,
}

/// Properties for js_error event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsErrorProps {
    pub message: String,
}

/// Properties for js_heartbeat event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsHeartbeatProps {
    pub seq: f64,
    pub uptime_sec: f64,
}

/// Properties for js_unhandled_rejection event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsUnhandledRejectionProps {
    pub reason: String,
}

/// Properties for panel_close event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelCloseProps {
    pub panel_id: String,
    pub via: String,
}

/// Properties for panel_open event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelOpenProps {
    pub panel_id: String,
    pub via: String,
}

/// Properties for rust_exit event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RustExitProps {
    pub pending_flushed: bool,
    pub prev_session_id: String,
    pub reason: String,
    pub uptime_s: f64,
    pub via: String,
}

/// Properties for rust_heartbeat event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RustHeartbeatProps {
    pub seq: f64,
}

/// Properties for rust_launch event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RustLaunchProps {
    pub version: String,
}

/// Properties for state_load event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateLoadProps {
    pub duration_ms: f64,
    pub tasks: f64,
}

/// Properties for state_sync event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateSyncProps {
    pub mock: bool,
    pub tasks: f64,
}

/// Properties for task_run event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskRunProps {
    pub task: String,
}

impl Event {
    /// Get the snake_case event name string
    pub fn as_str(&self) -> &'static str {
        match self {
            Event::AppUpdateCheck => "app_update_check",
            Event::AppUpdateChecked => "app_update_checked",
            Event::AppUpdateFailed => "app_update_failed",
            Event::AppUpdateInstalled => "app_update_installed",
            Event::DiagIdentityFailed => "diag_identity_failed",
            Event::DiagIpcTimeout => "diag_ipc_timeout",
            Event::DiagLogsOpenFailed => "diag_logs_open_failed",
            Event::DiagNativeMainUnresponsive => "diag_native_main_unresponsive",
            Event::DiagRustPanic => "diag_rust_panic",
            Event::DiagStateLoadFailed => "diag_state_load_failed",
            Event::DiagTaskSpawnFailed => "diag_task_spawn_failed",
            Event::DiagWebviewRecovered => "diag_webview_recovered",
            Event::DiagWebviewUnresponsive => "diag_webview_unresponsive",
            Event::JsError => "js_error",
            Event::JsHeartbeat => "js_heartbeat",
            Event::JsLaunch => "js_launch",
            Event::JsUnhandledRejection => "js_unhandled_rejection",
            Event::LogsOpen => "logs_open",
            Event::PanelClose => "panel_close",
            Event::PanelOpen => "panel_open",
            Event::RustExit => "rust_exit",
            Event::RustHeartbeat => "rust_heartbeat",
            Event::RustLaunch => "rust_launch",
            Event::StateLoad => "state_load",
            Event::StateSync => "state_sync",
            Event::TaskRun => "task_run",
        }
    }
}

impl std::fmt::Display for Event {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
